# Run the next command to create the image 
# docker buildx build -f backend/api/Dockerfile.dev -t <tag_name> . --load --build-arg UID=$(id -u) --build-arg GID=$(id -g)

# To run the container locally use the next command
# docker run -it -p 5000:5000 -p 5001:5001 --name <name_container> <tag_name> *bash // bash is optional

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS develop

ARG UID=1000
ARG GID=1000

RUN addgroup --gid ${GID} appgroup && adduser --uid ${UID} --ingroup appgroup --disabled-password --gecos "" appuser
WORKDIR /app

EXPOSE 5000
EXPOSE 5001

RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    git \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN chown -R appuser:appgroup /app

WORKDIR /app/backend

USER appuser

RUN dotnet restore backend.sln

ENV ASPNETCORE_URLS=https://+:5001;http://+:5000

RUN dotnet dev-certs https --trust

CMD ["tail", "-f", "/dev/null"]