FROM mcr.microsoft.com/dotnet/sdk:8.0 AS develop

WORKDIR /app

EXPOSE 5000

RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    git \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

COPY . .

WORKDIR /app/backend

RUN dotnet restore backend.sln

ENV ASPNETCORE_URLS=https://+:5001;http://+:5000

RUN dotnet dev-certs https --trust

CMD ["tail", "-f", "/dev/null"]