services:
  api:
    container_name: dgmx_practice
    build:
      context: .
      dockerfile: api/Dockerfile.dev
    user: "${UID}:${GID}"
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped
